services:
  sdu-chat-front:
    image: batyrbaev0520/sdu-chat-front:prod-1.0.0
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=https://chat-back.sdu.edu.kz/api
    restart: unless-stopped 